"""empty message

Revision ID: 403f66933435
Revises: bb25fe931e14
Create Date: 2023-04-16 00:01:47.037960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '403f66933435'
down_revision = 'bb25fe931e14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gambar',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('judul', sa.String(length=50), nullable=False),
    sa.Column('pathname', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gambar')
    # ### end Alembic commands ###
